---
title: "Publication list"
author: "Max Larter"
date: "1/30/2020"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE)
```

```{r loads_packs, include = F, echo = F}
# the first time you may need to re-reun this:
#install.packages("scholar")
#install.packages("tidyverse")
#install.packages("glue")


library(scholar)
library(tidyverse)
library(glue)
```

```{r special_chars}
# escape some special chars, german umlauts, ...
char2html <- function(x){
  dictionary <- data.frame(
    symbol = c("ä","ö","ü","Ä", "Ö", "Ü", "ß", "á", "ñ", "é", "è", "«", "»", "à"),
    html = c("&auml;","&ouml;", "&uuml;","&Auml;",
             "&Ouml;", "&Uuml;","&szlig;", "&aacute;", "&ntilde;", "&eacute;", "&egrave;", "&laquo;", "&raquo;", "&agrave;"))
  for(i in 1:dim(dictionary)[1]){
    x <- gsub(dictionary$symbol[i],dictionary$html[i],x)
  }
  x
}

```

```{r get_data}
# my google scholar user id from my profile url
# https://scholar.google.com/citations?user=-WJKy_EAAAAJ&hl=en
MaxLarter <- "-WJKy_EAAAAJ&hl"

# pull from google
html_1 <- get_publications(MaxLarter)

# pull pdf_urls matching GS titles
# first write this to file
write.csv(html_1 %>%
  as_tibble %>% arrange(desc(year)), file = "publications/publist.csv")
# then load the pdf or URLs we want in the publist # if you want to update new pub you NEED to add pdf link here or it will not show up
pdf_urls_file<-read.csv("publications/pdf_urls.csv", sep = ",", header = T)

html_1_2<-merge(html_1, pdf_urls_file, by = "title")

# convert to htlm table - the ugly way ;)
html_1_2 <- html_1_2 %>% mutate(author= ifelse(!str_detect(author, 'Larter'), 
                                             str_replace_all(author, ", \\.\\.\\.", ", M Larter, \\.\\.\\."),author)
  ) # this will add my name before the "et al." in long author lists when I'm towards the end


html_2 <- html_1_2 %>%
  as_tibble %>% arrange(desc(year)) %>%
  mutate(
#    author=str_replace_all(author, " (\\S) ", "\\1 "),
    author=str_replace_all(author, "([A-Z]) ([A-Z]) ", "\\1\\2 "),
    author=str_replace_all(author, ", \\.\\.\\.", " et al."),
    author=str_replace_all(author, "M Larter", "<b>M Larter</b>"), # make my name fat
    author=str_replace_all(author, "MD Larter", "<b>MD Larter</b>") # make my name fat
  ) %>% split(.$year) %>%
    map(function(x){
      x <- x %>%
        glue_data('<tr><td width="100%">{author} ({year}) <a href="https://scholar.google.com/scholar?oi=bibs&cluster={cid}&btnI=1&hl=en" target="_blank">{title}</a>, {journal}, {number} [<i>{cites} citation(s)</i>] <a href="{pdf_url}" target="_blank">(pdf)</a> </td></tr>') %>%
        str_replace_all("(, )+</p>", "</p>") %>%
        char2html()
      x <- c('<table><tbody>', x, '</tbody></table>')
      return(x);
    }) %>% rev

html_3 <- map2(names(html_2) %>% paste0("<h3>", ., "</h3>"), html_2, c) %>% unlist

html_4 <- c(
  paste0('<p><i>Last updated ',
         format(Sys.Date(), format="%d/%m/%Y"),
         ' &ndash; Pulled automatically from my <a href="https://scholar.google.com/citations?user=-WJKy_EAAAAJ&hl=en">Google Scholar profile</a>. See <a href="https://thackl.github.io/automatically-update-publications-with-R-scholar" target="_blank">this post</a> for how it works. See the code adapted to my usage <a href = "https://github.com/MaxLarter/maxlarter.github.io/blob/master/.R.Rmd" target="_blank">here</a>.</i></p>'), html_3)


```


```{r get header and footer, warning=F, echo = F}
dat <- noquote(readLines("index.html"))  # read in index.html to get header and footer setup 
dat2 <- noquote(str_replace_all(dat, "[\\r\\n\\t]+", " ")) # remove the added characters cause it gets messy otherwise
dat3 <- noquote(str_replace_all(dat2, "[\"]", '"')) # remove "escaped" quotes 
```

```{r paste_together}
text_to_insert <- html_4 # this is the bit of text we want to add from before

insert_after <- which(dat %in% '\t<div id="main" role="main" class="container">') # line in the index.html where the header ends: insert pubs table after this
insert_before <- grep('<div class="wrapper-footer">', dat3) # this is the line where the index.html file footer starts: insert before this
# function to do the insertion
insert_line_at <- function(dat, to_insert, insert_after, insert_before){
  pre <- dat[1:insert_after]
  post <- dat[(insert_before):length(dat)]
  return(c(pre, to_insert, post))
}
# run the insertion
dat_inserted <- insert_line_at(dat3, text_to_insert, insert_after=insert_after, insert_before = insert_before)

dat_inserted2 = gsub("\u00A0", " ", dat_inserted) # this removes the unbreakable space that appeared for some unkown reason...

writeLines(dat_inserted2, "publications/publications.html") # write to Publication list pages

######
# remember to commit & push to github and it's live!

```


```{r plot co_authors_network, eval = F}
co_auth<-get_coauthors(MaxLarter, n_coauthors = 5)
plot_coauthors(co_auth)
```


