theme: jekyll-theme-minimal

title: Welcome to my professional website.

description:Here is my [Google scholar profile](https://scholar.google.fr/citations?hl=en&user=-WJKy_EAAAAJ&view_op=list_works&sortby=pubdate).
