---
title: "Max Larter's CV"
docname: CV
name: Maximilian Larter
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r loads_packs, include = F, echo = F}
# the first time you may need to re-reun this:
#install.packages("scholar")
#install.packages("tidyverse")
#install.packages("glue")


library(scholar)
library(tidyverse)
library(glue)
library(vitae)
#devtools::install_github("nstrayer/datadrivencv")
```

```{r}

datadrivencv::use_datadriven_cv(
  full_name = "Maximilian Larter",
  data_location = 'https://docs.google.com/spreadsheets/d/11yfQvOxippBF5MKjtJX3wm06NARPvzLw6pI12wRvGnc',
  pdf_location = "https://github.com/MaxLarter/maxlarter.github.io/tree/master/cv/MaxLarter_CV.pdf",
  html_location = "https://maxlarter.github.io/cv/",
  source_location = "https://github.com/MaxLarter/cv",
  use_network_logo = FALSE,
  output_dir = paste0(getwd(),'/data/cv/'), create_output_dir = TRUE,
)
```

```{r}

# Knit the HTML version
rmarkdown::render("data/cv/cv.rmd",
                  params = list(pdf_mode = FALSE),
                  output_file = "cv_ML.html")

# Knit the PDF version to temporary html location
tmp_html_cv_loc <- fs::file_temp(ext = ".html")
rmarkdown::render("data/cv/cv.rmd",
                  params = list(pdf_mode = TRUE),
                  output_file = tmp_html_cv_loc)

# Convert to PDF using Pagedown
pagedown::chrome_print(input = tmp_html_cv_loc,
                       output = "cv.pdf")

```
